name: sheba_plus
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  toastification: ^2.3.0
  dio: ^5.7.0
  logger: ^2.5.0
  url_launcher: ^6.3.1
  phosphor_flutter: ^2.1.0
  connectivity_plus: ^6.1.0
  flutter_spinkit: ^5.2.1
  carousel_slider: ^5.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/carousel/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-Medium.ttf
          weight: 500
        - asset: assets/fonts/lato/Lato-Semibold.ttf
          weight: 600
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/lato/Lato-Hairline.ttf
          weight: 100

        # Italic Variants
        - asset: assets/fonts/lato/Lato-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/lato/Lato-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/lato/Lato-SemiboldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/lato/Lato-HairlineItalic.ttf
          style: italic
          weight: 100

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
